### ISSUE TITLE
Image Links

### ISSUE THREAD

**Issue by Biocodr** [HearthSim/hearthstonejson#14]
Hi there, good job on the project! Would it be possible to add image data (i.e., links) to the JSON? Or is there another smart way to retrieve these images (normal & gold) from another service via the provided ID?
Thanks and best regards!

**Comment by bergren2** [comment]
I'm sure the [Hearthhead](http://www.hearthhead.com/) folks don't want you doing this, but they use these IDs in their images. Here's an example:

- http://www.hearthhead.com/card=559/leeroy-jenkins
- http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_116.png
- http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_116_premium.png

Hearthead is the only service I know of that exposes these original IDs in addition to using their own ID system. Otherwise you'd have to map the cards by name.

**Comment by jleclanche** [comment]
An image renderer is far out of scope for HearthstoneJSON, so I'm closing this. But @bergren2's solution should work nicely.

**Comment by jleclanche** [comment]
So you guys know, there is now a `texture` item in every card. That is the **texture name**, which you can extract from the unity3d files (with [unitypack](https://github.com/hearthsim/python-unitypack) or disunity or something).

There is no **card** renderer, it's only the art section. A web-based card renderer is being created as part of the work on [Joust](https://github.com/hearthsim/joust).
