### ISSUE TITLE
flavor only in "thTh" in /all

### ISSUE THREAD

**Issue by vayzor** [HearthSim/hearthstonejson#28]
Hello,

I think the flavor is missing for every other language in here:
https://api.hearthstonejson.com/v1/latest/all/cards.collectible.json
I think "flavor" should be an array, like "name" or "text".

![image](https://cloud.githubusercontent.com/assets/7927910/14872503/ad0df154-0c88-11e6-81e6-66a9e0969014.png)

**Comment by hithroc** [comment]
The author closed the similar issue #24 a couple of days ago
This is the commit, that should've fixed this issue https://github.com/HearthSim/python-hearthstone/commit/cfce671c06550830f67b9ebb037ab6a5d2427e23
My guess is that the latest build at the moment (12574) was created before the issue was fixed.

**Comment by jleclanche** [comment]
I didn't regenerate the cards correctly. It's fixed for good now.
