### ISSUE TITLE
API unfriendly to Windows requests?

### ISSUE THREAD

**Issue by egermani** [HearthSim/hearthstonejson#33]
If I'm on my Mac, I can use curl or python's requests library to fetch the json without issue.

On my Windows machine, this request:

`requests.get("https://api.hearthstonejson.com/v1/latest/enUS/cards.json")`

returns this error:

`ConnectionError: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))`

I tried passing in "Mozilla/5.0" as a user-agent to see if the API was happier with that, but no dice.

I don't know much about networking, is there some obvious cause for this issue?

**Comment by jleclanche** [comment]
Hey! HearthstoneJSON SSL is configured to be TLS1.2 only, which your installation might not support. I would highly recommend looking into that. It might be caused by a version of python that is [too old](https://stackoverflow.com/questions/29153271/sending-tls-1-2-request-in-python-2-6), try using Python 3.4 or above.

Let me know if this helps. Otherwise, there's a cdn url for hearthstonejson which supports TLS 1.0 but it's not an official one, we only use it internally.

**Comment by egermani** [comment]
Thank you, Jerome! You were correct, my version of Python (2.7.6) was too outdated. I just installed Python 2.7.12 and the request went through without a hitch. Thank you for your help.
