### ISSUE TITLE
Internationalization of images

### ISSUE THREAD

**Issue by Angelima** [HearthSim/HearthstoneJSON#47]
Hi, 
Currently this URL produce images in English : https://art.hearthstonejson.com/v1/render/latest/enUS/256x/GVG_019.png

This seems not working for other languages like french for example.
This url procude an error (404) : https://art.hearthstonejson.com/v1/render/latest/frFr/256x/GVG_019.png

**Comment by jleclanche** [comment]
That's correct, we don't do non-english renders at the moment.

The main reason why is because layouting is currently broken for CJKT and we don't need it at the moment.

If you hop on [the developer discord](https://discord.gg/hearthsim-devs) and ping me we can chat about it. Let me know what you need this for etc, maybe I can help.
